insert into communities (id, name, description, admin_id) values (1, 'De-engineered client-driven emulation', 'moderator', 5);
insert into communities (id, name, description, admin_id) values (2, 'Operative attitude-oriented model', 'migration', 18);
insert into communities (id, name, description, admin_id) values (3, 'Re-engineered optimizing artificial intelligence', 'next generation', 3);
insert into communities (id, name, description, admin_id) values (4, 'Expanded zero tolerance moratorium', 'Virtual', 15);
insert into communities (id, name, description, admin_id) values (5, 'Multi-tiered cohesive matrices', 'support', 20);
insert into communities (id, name, description, admin_id) values (6, 'Open-source hybrid hardware', 'firmware', 17);
insert into communities (id, name, description, admin_id) values (7, 'Universal radical solution', 'clear-thinking', 17);
insert into communities (id, name, description, admin_id) values (8, 'De-engineered solution-oriented solution', 'multi-state', 19);
insert into communities (id, name, description, admin_id) values (9, 'Business-focused upward-trending software', 'flexibility', 17);
insert into communities (id, name, description, admin_id) values (10, 'Streamlined leading edge array', 'initiative', 3);
insert into communities (id, name, description, admin_id) values (11, 'Cross-platform bandwidth-monitored definition', 'adapter', 17);
insert into communities (id, name, description, admin_id) values (12, 'Focused 6th generation benchmark', 'composite', 17);
insert into communities (id, name, description, admin_id) values (13, 'Centralized intermediate contingency', 'high-level', 11);
insert into communities (id, name, description, admin_id) values (14, 'Re-engineered tangible implementation', 'fresh-thinking', 20);
insert into communities (id, name, description, admin_id) values (15, 'Decentralized incremental strategy', 'initiative', 1);
insert into communities (id, name, description, admin_id) values (16, 'Pre-emptive 4th generation definition', 'Business-focused', 4);
insert into communities (id, name, description, admin_id) values (17, 'Centralized 4th generation intranet', '6th generation', 17);
insert into communities (id, name, description, admin_id) values (18, 'Customer-focused systemic hierarchy', 'approach', 20);
insert into communities (id, name, description, admin_id) values (19, 'Horizontal 4th generation matrices', 'structure', 19);
insert into communities (id, name, description, admin_id) values (20, 'Diverse incremental projection', 'local', 18);
