insert into job_users (id, user_id, work_experience, speciality) values (1, 1, 'Support', 'Chief Design Engineer');
insert into job_users (id, user_id, work_experience, speciality) values (2, 2, 'Training', 'Research Nurse');
insert into job_users (id, user_id, work_experience, speciality) values (3, 3, 'Services', 'Senior Cost Accountant');
insert into job_users (id, user_id, work_experience, speciality) values (4, 4, 'Business Development', 'Accountant IV');
insert into job_users (id, user_id, work_experience, speciality) values (5, 5, 'Accounting', 'Chief Design Engineer');
insert into job_users (id, user_id, work_experience, speciality) values (6, 6, 'Training', 'Senior Cost Accountant');
insert into job_users (id, user_id, work_experience, speciality) values (7, 7, 'Services', 'Sales Associate');
insert into job_users (id, user_id, work_experience, speciality) values (8, 8, 'Engineering', 'Senior Developer');
insert into job_users (id, user_id, work_experience, speciality) values (9, 9, 'Product Management', 'Senior Sales Associate');
insert into job_users (id, user_id, work_experience, speciality) values (10, 10, 'Legal', 'Associate Professor');
insert into job_users (id, user_id, work_experience, speciality) values (11, 11, 'Legal', 'Desktop Support Technician');
insert into job_users (id, user_id, work_experience, speciality) values (12, 12, 'Training', 'Compensation Analyst');
insert into job_users (id, user_id, work_experience, speciality) values (13, 13, 'Human Resources', 'Web Developer III');
insert into job_users (id, user_id, work_experience, speciality) values (14, 14, 'Services', 'Senior Editor');
insert into job_users (id, user_id, work_experience, speciality) values (15, 15, 'Training', 'Biostatistician IV');
insert into job_users (id, user_id, work_experience, speciality) values (16, 16, 'Training', 'GIS Technical Architect');
insert into job_users (id, user_id, work_experience, speciality) values (17, 17, 'Support', 'Social Worker');
insert into job_users (id, user_id, work_experience, speciality) values (18, 18, 'Accounting', 'Biostatistician III');
insert into job_users (id, user_id, work_experience, speciality) values (19, 19, 'Training', 'Cost Accountant');
insert into job_users (id, user_id, work_experience, speciality) values (20, 20, 'Engineering', 'Registered Nurse');
